// This file is automatically generated. Do not change this file!

import { Content } from '@frontend/types/content';

export const CONTENT: Content = {
  properties: {
    title: 'Learning Platform',
  },
  pages: {
    home: {
      properties: {
        title: 'Home',
      },
      contents: [
        {
          type: 'text',
          properties: {
            text: 'Welcome to the Learning Platform!',
          },
        },
      ],
    },
    about: {
      properties: {
        title: 'About',
      },
      contents: [
        {
          type: 'text',
          properties: {
            text: 'About the Learning Platform',
          },
        },
      ],
      me: {
        properties: {
          title: 'Me',
        },
        contents: [
          {
            type: 'text',
            properties: {
              text: 'About me',
            },
          },
        ],
      },
    },
  },
} as const;
