// This file is automatically generated. Do not change this file!

import { Content } from '@frontend/types/content';
import {
  ContentTypesSpacing,
  ContentTypesText,
} from '@frontend/components/_content-renderer';

export const CONTENT: Content = {
  properties: {
    title: 'Learning Platform',
  },
  pages: {
    home: {
      properties: {
        title: 'Home',
      },
      contents: [
        {
          type: ContentTypesText.Paragraph,
          properties: {
            text: 'Welcome to the Learning Platform!',
          },
        },
      ],
    },
    about: {
      properties: {
        title: 'About',
      },
      contents: [
        {
          type: ContentTypesSpacing.Container,
          properties: {
            width: 1,
          },
          contents: [
            {
              type: ContentTypesText.Paragraph,
              properties: {
                text: 'About the Learning Platform',
              },
            },
            {
              type: ContentTypesSpacing.Horizontal,
              properties: {
                width: 1,
              },
              contents: [
                {
                  type: ContentTypesText.Paragraph,
                  properties: {
                    text: 'About the Learning Platform',
                  },
                },
                {
                  type: ContentTypesText.Paragraph,
                  properties: {
                    text: 'About the Learning Platform',
                  },
                },
              ],
            },
          ],
        },
      ],
      me: {
        properties: {
          title: 'Me',
        },
        contents: [
          {
            type: ContentTypesText.Paragraph,
            properties: {
              text: 'About me',
            },
          },
        ],
      },
    },
  },
} as const;
